apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy
  labels:
   app: demo
spec: 
  replicas: 7
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
     labels:
      app: demo
    spec:
      containers: 
      - name: dockerdemo
        image: wakanda1forever/dockerdemo:v1
        ports:
        - containerPort: 8080
